### ISSUE TITLE
installation problem 

### ISSUE THREAD

**Issue by adesalegn** [Zhangxf-ccnu/DiffGraph#2]
Hi ,
I desperately want to use the DiffGraph package but it seems not working in the current or early version of R?
After download, installation not possible in my case. Below I would like to show the error and warnings messages.
best,
 AD
```
install.packages("D:/Users/AB/Documents/ab/DiffGraph_1.1.1.tar.gz", type = "source")
Warning in install.packages : package ‘D:/Users/AB/Documents/ab/DiffGraph_1.1.1.tar.gz’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages
 library(DiffGraph)
Error in library(DiffGraph) : there is no package called ‘DiffGraph’ 
```

**Comment by Zhangxf-ccnu** [comment]
Hi adesalegn,

     We have changed the way to the install the package. For detail, please refer to the readme file (https://github.com/Zhangxf-ccnu/DiffGraph).

Regards,

xiaofei
